### PR TITLE
Oracle and BigQuery fixes

### LINKED ISSUE #98: BigQuery Errors
It looks like some errors are getting thrown in some of the date comparisons.  BigQuery will only compare two of the exact same type.  It looks like some of the casting was taken out recently: #92

```
BMS:
bigquery

Error:
java.sql.SQLException: [Simba]BigQueryJDBCDriver(100032) Error executing query job. Message: No matching signature for operator > for argument types: DATETIME, DATE. Supported signatures: ANY ANY at [10:11]

SQL:

/*********
PLAUSIBLE_VALUE_HIGH
get number of records and the proportion to total number of eligible records that exceed this threshold

Parameters used in this template:
cdmDatabaseSchema = uchealth_omop
cdmTableName = DEVICE_EXPOSURE
cdmFieldName = device_exposure_start_datetime
plausibleValueHigh = DATEADD(dd,1,GETDATE())
**********/

select num_violated_rows, case when denominator.num_rows = 0 then 0 else 1.0*num_violated_rows/denominator.num_rows end  as pct_violated_rows, 
  denominator.num_rows as num_denominator_rows
from
(
	select COUNT(violated_rows.violating_field) as num_violated_rows
	from
	(
		select 'DEVICE_EXPOSURE.device_exposure_start_datetime' as violating_field, cdmtable.*
    from uchealth_omop.device_exposure cdmtable
    where cdmtable.device_exposure_start_datetime > DATE_ADD(cast(CURRENT_DATE() as date), interval 1 DAY)
	) violated_rows
) violated_row_count,
(
	select COUNT(*) as num_rows
	from uchealth_omop.device_exposure
  where device_exposure_start_datetime is not null
) denominator
;
```

### PR DESCRIPTION
**Pull request by alondhe**
#98 -- dynamic casting of datetimes in queries that use comparisons. This will ensure BigQuery date comparisons will work.
#100 -- use upper case for cdm field names to allow us to use quotes around the field name in field_cdm_field check. This will ensure we can quote the CDM field "offset" and not run into a keyword error on Postgres **and** not run into a case sensitivity issue in Oracle

### CODE REVIEW

**Comment by alondhe** [comment]
Poking the bear 
@clairblacketer @fdefalco

**Comment by alondhe** [comment]
Re-poking the bear
@clairblacketer @fdefalco

**Comment by kirenotneb** [comment]
I made an alternate approach in PR #162 . If this PR contains the appropriate fix can it be merged into master and then released with a tag? We have the exact same issue in our Oracle instance of CDM 5.3.1.

**Comment by kirenotneb** [comment]
@clairblacketer  @fdefalco any chance this PR or PR #183 can get approved and merged?

**Review by fdefalco — APPROVED** [review]

**Pull request merged**
