### PR TITLE
Add Docker build to run shiny dashboard

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add a container build to easily run the dashboard without needing to worry about system dependencies. Specifically:

 - The [Dockerfile](https://github.com/researchapps/DataQualityDashboard/blob/945d2f1a56977d0f0156558a6a5f41536713960e/Dockerfile) builds the container from the repository source.
 - The entrypoint runs an Rscript command to start the shiny server.
 - The default results.json is provided in the container, and the user is given instructions for how to bind a custom file if desired.

Please see the README for updated documentation on doing the build and interacting with the container! I've pushed a demo to my Docker Hub if you want to run it quickly without building:

```bash
$ docker run -it --rm -p 7769:7769 vanessa/data-quality-dashboard
Loading required package: DatabaseConnector
Loading required package: shiny

Listening on http://0.0.0.0:7769
```
And then of course you can open up to localhost:7769 to see the dashboard. You can bind custom data (also in the README) as follows:

```bash
$ docker run -it --rm -p 7769:7769 -v $PWD/results.json:/code/inst/shinyApps/results.json vanessa/data-quality-dashboard
```
To make it possible for the container to control the host and ports, I expose these through the `DataQualityDashboard::viewDqDashboard` function. Also, since we are working in a container, the jsonPath doesn't need a custom folder or source name - the user can bind it wherever it might be from their host.

```R
DataQualityDashboard::viewDqDashboard(jsonPath = filename, port=7769, host="0.0.0.0")
```

I hope this is a good start with containerization! I don't have a good sense for the database interaction, but if we can discuss and I know how to test, I could test how to get this working via a container as well.

### CODE REVIEW

**Comment by vsoch** [comment]
I just pushed a quick update to add the DESCRIPTION file first, so the install of the dependencies is cached. This will hugely speed up development with the container (assuming DESCRIPTION is not changed).

**Comment by fdefalco** [comment]
This PR has unfortunately gone unmerged and now has a few conflicts.  If we still have interest in its inclusion, please review and rebase on current master and I will ensure the merge takes place.

**Comment by vsoch** [comment]
It looks like the install documentation is moved into docs - how do I generate this html?

**Comment by vsoch** [comment]
It looks like files (markdown) are under vingettes? Do I need to then run a generation command locally?

**Comment by vsoch** [comment]
I can update the PR, but I'm totally missing any developer documentation about how to add / contribute to the docs! Would possibly be a good idea to add that :)

**Comment by fdefalco** [comment]
I believe the recent consensus has been to not include docker image definitions in the individual R packages but rather add them to the OHDSI-in-a-box image definition. (https://github.com/OHDSI/OHDSI-in-a-Box)

**Pull request closed without merging**
